version: '3.8'

services:
  db: 
    image: postgres:15-alpine 
    container_name: qompa_postgres_db 
    restart: always
    environment:
      POSTGRES_DB: qompa_vouchers_db 
      POSTGRES_USER: qompa_user           
      POSTGRES_PASSWORD: qompa_password   
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: 